"""Tests for the SYNTHETIC TIKG generator, its validation and the dataset loader interface."""
import copy
import json
import re
import warnings

import numpy as np
import pytest

from iocevaluator.datasets import Dataset, SyntheticDataError, load_dataset
from iocevaluator.splits import group_stratified_folds
from iocevaluator.synthetic_tikg import (PROFILES, check_reproducible, cvss31_base_score, generate, parse_template,
                                         read_dataset, validate, write_dataset)
from iocevaluator.synthetic_tikg.generator import PATH_TEMPLATES, dumps

MANUSCRIPT_COUNTS = {"threat_actor": 271, "vulnerability": 2298, "attack_method": 68, "file": 336,
                     "attack_type": 229, "device": 344, "platform": 182}


@pytest.fixture(scope="module")
def dev():
    return generate("dev", 42)


@pytest.fixture(scope="module")
def scale():
    return generate("manuscript_scale", 42)


def _fails(report):
    return {c.name for c in report.failures()}


# ---------------------------------------------------------------------------------------------- profiles / counts
def test_dev_profile_size_is_300_to_500_nodes(dev):
    assert 300 <= len(dev.nodes) <= 500
    assert validate(dev).ok, validate(dev).summary()


def test_manuscript_scale_exact_counts(scale):
    from collections import Counter
    assert Counter(n["type"] for n in scale.nodes) == MANUSCRIPT_COUNTS
    assert len(scale.nodes) == 3728 and len(scale.edges) == 11624
    assert len(scale.attack_paths) == 76
    rep = validate(scale)
    assert rep.ok, rep.summary()


def test_edge_relation_and_triplet_distribution(scale):
    from collections import Counter
    c = Counter(e["triplet"] for e in scale.edges)
    assert set(c) == {f"T{i}" for i in range(1, 12)}          # X1 extension not generated by default
    assert sum(c.values()) == 11624


def test_average_degree_matches_manuscript(scale):
    assert abs(2 * len(scale.edges) / len(scale.nodes) - 6.24) < 0.05


# ---------------------------------------------------------------------------------------------- determinism
def test_same_seed_reproduces_and_different_seed_differs():
    assert check_reproducible("dev", 42)
    a = dumps(generate("dev", 1).edges)
    b = dumps(generate("dev", 2).edges)
    assert a != b


def test_written_files_are_byte_identical_across_runs(tmp_path, dev):
    write_dataset(generate("dev", 42), tmp_path / "a")
    write_dataset(generate("dev", 42), tmp_path / "b")
    for f in ("nodes", "edges", "labels", "campaigns", "attack_paths", "metadata"):
        assert (tmp_path / "a" / f"{f}.json").read_bytes() == (tmp_path / "b" / f"{f}.json").read_bytes()


def test_roundtrip_and_metadata_flags(tmp_path, dev):
    out = write_dataset(dev, tmp_path / "d")
    meta = json.loads((out / "metadata.json").read_text())
    assert meta["dataset_type"] == "synthetic"
    assert meta["purpose"] == "development_and_pipeline_validation"
    assert meta["not_for_reported_experimental_results"] is True
    assert meta["seed"] == 42
    back = read_dataset(out)
    assert validate(back).ok


# ---------------------------------------------------------------------------------------------- semantic structure
def test_related_campaigns_share_more_than_unrelated(scale):
    sep = validate(scale).stats["similarity_separation"]
    assert sep["jaccard_related_campaigns"] > 5 * sep["jaccard_unrelated_campaigns"]
    assert sep["frac_related_campaign_pairs_sharing_vuln"] > 0.5 > sep["frac_unrelated_campaign_pairs_sharing_vuln"]


def test_edges_are_not_uniform_random(scale):
    loc = validate(scale).stats["edge_locality"]
    # uniform random edges over 60 campaigns would give ~1.7% in-campaign
    assert loc["campaign"] > 0.5 and loc["cross_family"] < 0.15


# ---------------------------------------------------------------------------------------------- synthetic realism / safety
def test_identifiers_are_clearly_synthetic(dev):
    for n in dev.nodes:
        assert n["attrs"]["synthetic"] is True
        if n["type"] == "vulnerability":
            m = re.fullmatch(r"CVE-(\d{4})-\d{5}", n["name"])
            assert m and 2090 <= int(m.group(1)) <= 2099
            assert 0.0 <= n["attrs"]["cvss_base_score"] <= 10.0
        if n["type"] == "attack_method":
            assert re.fullmatch(r"T1\d{3}(\.\d{3})?", n["attrs"]["technique_id"])
        if n["type"] == "file" and n["subtype"] == "domain":
            assert n["name"].endswith(".example")
        if n["type"] == "file" and n["subtype"] == "email":
            assert n["name"].endswith("@example.invalid")
        if n["type"] == "file" and n["subtype"] == "hash":
            assert re.fullmatch(r"[0-9a-f]{32}|[0-9a-f]{40}|[0-9a-f]{64}", n["name"])


def test_cvss_formula_and_stored_scores(dev):
    assert cvss31_base_score("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H") == 9.8
    assert cvss31_base_score("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H") == 10.0
    assert cvss31_base_score("CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N") == 5.5
    for n in dev.nodes:
        if n["type"] == "vulnerability":
            assert cvss31_base_score(n["attrs"]["cvss_vector"]) == n["attrs"]["cvss_base_score"]


def test_templates_are_valid_table2_triplets():
    for specs in PATH_TEMPLATES.values():
        for s in specs:
            types, steps = parse_template(s)
            assert len(types) == len(steps) + 1


# ---------------------------------------------------------------------------------------------- validation catches corruption
def _mut(ds):
    return copy.deepcopy(ds)


def test_validation_detects_schema_violation(dev):
    d = _mut(dev)
    e = next(e for e in d.edges if e["triplet"] == "T1")
    e["relation"] = "enables"
    assert "every_edge_respects_schema_T1_T11" in _fails(validate(d))


def test_validation_detects_wrong_direction(dev):
    d = _mut(dev)
    e = next(e for e in d.edges if e["triplet"] == "T2")
    e["source"], e["target"] = e["target"], e["source"]
    assert "every_edge_respects_schema_T1_T11" in _fails(validate(d))


def test_validation_detects_dangling_and_duplicates(dev):
    d = _mut(dev)
    d.edges[0]["target"] = "nope"
    assert "no_dangling_edge_endpoints" in _fails(validate(d))
    d = _mut(dev)
    d.nodes.append(copy.deepcopy(d.nodes[0]))
    assert "no_duplicate_node_ids" in _fails(validate(d))
    d = _mut(dev)
    d.edges.append(copy.deepcopy(d.edges[0]))
    assert "no_duplicate_edges" in _fails(validate(d))


def test_validation_detects_bad_campaign_label_and_counts(dev):
    d = _mut(dev)
    d.nodes[0]["campaign"] = "camp-999"
    assert "campaign_ids_exist_for_all_nodes" in _fails(validate(d))
    d = _mut(dev)
    del d.labels["labels"][d.nodes[3]["id"]]
    assert "labels_exist_for_every_node" in _fails(validate(d))
    d = _mut(dev)
    d.nodes.pop()
    assert "node_counts_exact_by_type" in _fails(validate(d))


def test_validation_detects_bad_attack_paths(dev):
    d = _mut(dev)
    d.attack_paths[0]["steps"][0]["target"] = d.attack_paths[-1]["nodes"][-1]
    assert "attack_paths_use_only_existing_edges_and_valid_templates" in _fails(validate(d))
    d = _mut(dev)
    d.attack_paths.pop()
    assert "attack_path_length_distribution" in _fails(validate(d))
    d = _mut(dev)
    d.metadata["not_for_reported_experimental_results"] = False
    assert "metadata_synthetic_flags" in _fails(validate(d))


def test_attack_path_distribution_and_validity(scale):
    from collections import Counter
    c = Counter("2" if p["n_edges"] == 2 else "3" if p["n_edges"] == 3 else ">=4" for p in scale.attack_paths)
    assert c == {"2": 32, "3": 26, ">=4": 18}
    edges = {(e["source"], e["relation"], e["target"]) for e in scale.edges}
    for p in scale.attack_paths:
        assert all((s["source"], s["relation"], s["target"]) in edges for s in p["steps"])


def test_label_space_matches_table7_class_counts(scale):
    for t, k in {"threat_actor": 11, "vulnerability": 47, "attack_method": 3, "file": 13, "attack_type": 11,
                 "device": 14, "platform": 9}.items():
        assert len(scale.labels["classes"][t]) == k


# ---------------------------------------------------------------------------------------------- optional extension
def test_x1_extension_is_opt_in_and_valid():
    d = generate("dev", 42, include_x1=True)
    assert any(e["triplet"] == "X1" for e in d.edges) and d.metadata["include_x1_extension"] is True
    assert validate(d).ok
    assert not any(e["triplet"] == "X1" for e in generate("dev", 42).edges)


# ---------------------------------------------------------------------------------------------- loader interface
@pytest.fixture(scope="module")
def on_disk(tmp_path_factory):
    root = tmp_path_factory.mktemp("syn")
    write_dataset(generate("dev", 42), root / "dev")
    return root


def test_loader_returns_pipeline_objects(on_disk):
    ds = load_dataset("synthetic", profile="dev", root=on_disk)
    assert isinstance(ds, Dataset) and ds.is_synthetic
    assert ds.tikg.n == 350 and len(ds.tikg.triplets) == 1091
    assert ds.labels.labelled.all() and ds.labels.K == 108
    assert len(ds.reference_paths) == 76
    assert ds.severity_known.sum() == 210 and ds.severity.max() <= 1.0
    assert "NOT FOR REPORTED RESULTS" in ds.banner()
    with pytest.raises(SyntheticDataError):
        ds.require_real()


def test_loader_refuses_unflagged_directory(on_disk, tmp_path):
    import shutil
    shutil.copytree(on_disk / "dev", tmp_path / "dev")
    meta = json.loads((tmp_path / "dev" / "metadata.json").read_text())
    meta["not_for_reported_experimental_results"] = False
    (tmp_path / "dev" / "metadata.json").write_text(json.dumps(meta))
    with pytest.raises(SyntheticDataError):
        load_dataset("synthetic", profile="dev", root=tmp_path)


def test_real_branch_uses_same_interface(on_disk, tmp_path):
    syn = load_dataset("synthetic", profile="dev", root=on_disk)
    syn.tikg.save(tmp_path / "tikg.json")                       # stand-in for a real file in the native format
    lab = json.loads((on_disk / "dev" / "labels.json").read_text())
    (tmp_path / "labels.json").write_text(json.dumps(lab))
    real = load_dataset("real", tikg_path=tmp_path / "tikg.json", labels_path=tmp_path / "labels.json", name="x")
    assert isinstance(real, Dataset) and not real.is_synthetic
    assert real.require_real() is real
    with pytest.raises(FileNotFoundError):
        load_dataset("synthetic", profile="nope", root=on_disk)


def test_group_cv_is_campaign_isolated(on_disk):
    ds = load_dataset("synthetic", profile="dev", root=on_disk)
    camp = ds.tikg.campaigns()
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        folds = group_stratified_folds(ds.tikg, ds.labels, n_splits=10, seed=0)
    assert len(folds) == 10
    for f in folds:
        assert not (set(camp[f.train]) & set(camp[f.test]))
        assert not (set(camp[f.val]) & set(camp[f.test]))
